try {
    hello()
} catch (e) {
    console.log(e);
}

try{
    anotherFunction()

} catch{
    console.log("esto es un error");
}